export interface PracticeQuestion {
  id: string;
  name: string;
  topic: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  pattern: string;
  leetcodeNumber: number;
  tip: string;
}

export const PRACTICE_TOPICS = [
  'All Topics',
  'Arrays & Hashing',
  'Two Pointers & Sliding Window',
  'Binary Search',
  'Linked List',
  'Trees & BST',
  'Graphs',
  'Dynamic Programming',
  'Heap / Priority Queue',
  'Stack & Queue',
  'Backtracking',
] as const;

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  // ─── Arrays & Hashing ───
  {
    id: 'pq_1',
    name: 'Two Sum',
    topic: 'Arrays & Hashing',
    difficulty: 'Easy',
    pattern: 'Hash Map Complement',
    leetcodeNumber: 1,
    tip: 'Store seen values and their indices in a hash map for O(n) single-pass lookup.',
  },
  {
    id: 'pq_2',
    name: 'Group Anagrams',
    topic: 'Arrays & Hashing',
    difficulty: 'Medium',
    pattern: 'Sorted String / Character Frequency Map',
    leetcodeNumber: 49,
    tip: 'Use sorted characters or 26-element character count tuples as the hash map key.',
  },
  {
    id: 'pq_3',
    name: 'Product of Array Except Self',
    topic: 'Arrays & Hashing',
    difficulty: 'Medium',
    pattern: 'Prefix & Suffix Products',
    leetcodeNumber: 238,
    tip: 'Build prefix products from the left, then accumulate suffix products from the right in O(1) extra space.',
  },
  {
    id: 'pq_4',
    name: 'Longest Consecutive Sequence',
    topic: 'Arrays & Hashing',
    difficulty: 'Medium',
    pattern: 'Hash Set Sequence Start Check',
    leetcodeNumber: 128,
    tip: 'Insert all into a Set. Only initiate counting when (num - 1) is not present.',
  },
  {
    id: 'pq_5',
    name: 'Subarray Sum Equals K',
    topic: 'Arrays & Hashing',
    difficulty: 'Medium',
    pattern: 'Prefix Sum & Frequency Map',
    leetcodeNumber: 560,
    tip: 'Look for (prefixSum - k) in a running frequency map initialized with {0: 1}.',
  },

  // ─── Two Pointers & Sliding Window ───
  {
    id: 'pq_6',
    name: 'Best Time to Buy and Sell Stock',
    topic: 'Two Pointers & Sliding Window',
    difficulty: 'Easy',
    pattern: 'Running Minimum',
    leetcodeNumber: 121,
    tip: 'Track the lowest purchase price seen so far and evaluate profit at each step.',
  },
  {
    id: 'pq_7',
    name: 'Longest Substring Without Repeating Characters',
    topic: 'Two Pointers & Sliding Window',
    difficulty: 'Medium',
    pattern: 'Dynamic Sliding Window',
    leetcodeNumber: 3,
    tip: 'Expand right pointer; advance left pointer beyond duplicate position using a hash map of indices.',
  },
  {
    id: 'pq_8',
    name: 'Container With Most Water',
    topic: 'Two Pointers & Sliding Window',
    difficulty: 'Medium',
    pattern: 'Shrinking Boundary Two Pointers',
    leetcodeNumber: 11,
    tip: 'Start at extremes; always shift the pointer with the shorter vertical wall.',
  },
  {
    id: 'pq_9',
    name: '3Sum',
    topic: 'Two Pointers & Sliding Window',
    difficulty: 'Medium',
    pattern: 'Sorted Array + Two Pointers',
    leetcodeNumber: 15,
    tip: 'Sort first; lock in one number and use two pointers for the remaining pair, skipping duplicates.',
  },
  {
    id: 'pq_10',
    name: 'Trapping Rain Water',
    topic: 'Two Pointers & Sliding Window',
    difficulty: 'Hard',
    pattern: 'Two Pointers Max Boundaries',
    leetcodeNumber: 42,
    tip: 'Maintain leftMax and rightMax; the water trapped depends on the smaller of the two bounds.',
  },

  // ─── Binary Search ───
  {
    id: 'pq_11',
    name: 'Binary Search',
    topic: 'Binary Search',
    difficulty: 'Easy',
    pattern: 'Classic Divide & Conquer',
    leetcodeNumber: 704,
    tip: 'Avoid integer overflow with mid = left + Math.floor((right - left) / 2).',
  },
  {
    id: 'pq_12',
    name: 'Search in Rotated Sorted Array',
    topic: 'Binary Search',
    difficulty: 'Medium',
    pattern: 'Modified Binary Search',
    leetcodeNumber: 33,
    tip: 'At any pivot, at least one half (left or right) is guaranteed to be strictly sorted.',
  },
  {
    id: 'pq_13',
    name: 'Find Minimum in Rotated Sorted Array',
    topic: 'Binary Search',
    difficulty: 'Medium',
    pattern: 'Inflection Point Search',
    leetcodeNumber: 153,
    tip: 'Compare mid with right; if nums[mid] > nums[right], the minimum lies strictly in the right half.',
  },
  {
    id: 'pq_14',
    name: 'Koko Eating Bananas',
    topic: 'Binary Search',
    difficulty: 'Medium',
    pattern: 'Binary Search on Answer Space',
    leetcodeNumber: 875,
    tip: 'Search speed k between 1 and max(piles); verify feasibility in O(n).',
  },
  {
    id: 'pq_15',
    name: 'Median of Two Sorted Arrays',
    topic: 'Binary Search',
    difficulty: 'Hard',
    pattern: 'Binary Search on Partition',
    leetcodeNumber: 4,
    tip: 'Binary search for the ideal partition line in the smaller array so left halves balance right halves.',
  },

  // ─── Linked List ───
  {
    id: 'pq_16',
    name: 'Reverse Linked List',
    topic: 'Linked List',
    difficulty: 'Easy',
    pattern: 'Three Pointers (prev, curr, next)',
    leetcodeNumber: 206,
    tip: 'Iteratively invert pointers while preserving the next reference.',
  },
  {
    id: 'pq_17',
    name: 'Merge Two Sorted Lists',
    topic: 'Linked List',
    difficulty: 'Easy',
    pattern: 'Dummy Head Pointer',
    leetcodeNumber: 21,
    tip: 'Use a dummy sentinel node to simplify list building without special head edge cases.',
  },
  {
    id: 'pq_18',
    name: 'Linked List Cycle',
    topic: 'Linked List',
    difficulty: 'Easy',
    pattern: "Floyd's Tortoise and Hare",
    leetcodeNumber: 141,
    tip: 'Advance slow by 1 and fast by 2; if they meet, a cycle exists.',
  },
  {
    id: 'pq_19',
    name: 'Remove Nth Node From End of List',
    topic: 'Linked List',
    difficulty: 'Medium',
    pattern: 'Fast-Forward Pointer Offset',
    leetcodeNumber: 19,
    tip: 'Advance fast pointer n steps ahead, then move both together until fast reaches the tail.',
  },
  {
    id: 'pq_20',
    name: 'LRU Cache',
    topic: 'Linked List',
    difficulty: 'Medium',
    pattern: 'Hash Map + Doubly Linked List',
    leetcodeNumber: 146,
    tip: 'Hash Map provides O(1) key access; Doubly Linked List gives O(1) node relocation and eviction.',
  },

  // ─── Trees & BST ───
  {
    id: 'pq_21',
    name: 'Invert Binary Tree',
    topic: 'Trees & BST',
    difficulty: 'Easy',
    pattern: 'Recursive DFS Post-Order',
    leetcodeNumber: 226,
    tip: 'Swap left and right children recursively for all subtrees.',
  },
  {
    id: 'pq_22',
    name: 'Maximum Depth of Binary Tree',
    topic: 'Trees & BST',
    difficulty: 'Easy',
    pattern: 'DFS / BFS Level Order',
    leetcodeNumber: 104,
    tip: '1 + Math.max(depth(root.left), depth(root.right)).',
  },
  {
    id: 'pq_23',
    name: 'Lowest Common Ancestor of a BST',
    topic: 'Trees & BST',
    difficulty: 'Medium',
    pattern: 'BST Value Splitting',
    leetcodeNumber: 235,
    tip: 'If both p and q are less than root, go left; if both greater, go right; otherwise current root is the split LCA.',
  },
  {
    id: 'pq_24',
    name: 'Validate Binary Search Tree',
    topic: 'Trees & BST',
    difficulty: 'Medium',
    pattern: 'Min/Max Range Propagation',
    leetcodeNumber: 98,
    tip: 'Pass strictly bounded (min, max) limits down each recursive subtree branch.',
  },
  {
    id: 'pq_25',
    name: 'Binary Tree Level Order Traversal',
    topic: 'Trees & BST',
    difficulty: 'Medium',
    pattern: 'BFS Queue by Level Size',
    leetcodeNumber: 102,
    tip: 'Process queue in batches matching queue.length at the start of each level iteration.',
  },

  // ─── Graphs ───
  {
    id: 'pq_26',
    name: 'Number of Islands',
    topic: 'Graphs',
    difficulty: 'Medium',
    pattern: 'Grid DFS / BFS Sink Visited',
    leetcodeNumber: 200,
    tip: 'When encountering "1", increment island count and recursively sink adjacent land cells to "0".',
  },
  {
    id: 'pq_27',
    name: 'Clone Graph',
    topic: 'Graphs',
    difficulty: 'Medium',
    pattern: 'Hash Map Node Mapping + DFS',
    leetcodeNumber: 133,
    tip: 'Map original node references to cloned instances to prevent duplicate creation and cycles.',
  },
  {
    id: 'pq_28',
    name: 'Course Schedule',
    topic: 'Graphs',
    difficulty: 'Medium',
    pattern: "Topological Sort (Kahn's In-Degree / DFS Cycle Detection)",
    leetcodeNumber: 207,
    tip: 'Calculate in-degrees; enqueue courses with 0 prerequisites. If visited count < numCourses, a cycle exists.',
  },
  {
    id: 'pq_29',
    name: 'Rotting Oranges',
    topic: 'Graphs',
    difficulty: 'Medium',
    pattern: 'Multi-Source BFS',
    leetcodeNumber: 994,
    tip: 'Enqueue all initially rotten oranges simultaneously and traverse outwards minute-by-minute.',
  },
  {
    id: 'pq_30',
    name: 'Pacific Atlantic Water Flow',
    topic: 'Graphs',
    difficulty: 'Medium',
    pattern: 'Reverse Flow DFS from Oceans',
    leetcodeNumber: 417,
    tip: 'Start from ocean boundaries and flow upwards towards higher or equal ground; take set intersection.',
  },

  // ─── Dynamic Programming ───
  {
    id: 'pq_31',
    name: 'Climbing Stairs',
    topic: 'Dynamic Programming',
    difficulty: 'Easy',
    pattern: 'Fibonacci State Transition',
    leetcodeNumber: 70,
    tip: 'ways(n) = ways(n-1) + ways(n-2). Keep only previous two states for O(1) space.',
  },
  {
    id: 'pq_32',
    name: 'House Robber',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    pattern: 'Non-Adjacent Max Decision',
    leetcodeNumber: 198,
    tip: 'dp[i] = Math.max(dp[i-1], dp[i-2] + nums[i]).',
  },
  {
    id: 'pq_33',
    name: 'Coin Change',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    pattern: 'Bottom-Up Unbounded Knapsack',
    leetcodeNumber: 322,
    tip: 'Initialize dp table with amount + 1. For each coin, dp[i] = Math.min(dp[i], dp[i - coin] + 1).',
  },
  {
    id: 'pq_34',
    name: 'Longest Increasing Subsequence',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    pattern: 'Binary Search Patience Sort',
    leetcodeNumber: 300,
    tip: 'Maintain smallest tail elements of increasing sequences; use binary search for O(n log n).',
  },
  {
    id: 'pq_35',
    name: 'Word Break',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    pattern: 'Prefix Partition DP',
    leetcodeNumber: 139,
    tip: 'dp[i] is true if any prefix dp[j] is true AND substring(j, i) exists in the dictionary.',
  },

  // ─── Heap / Priority Queue ───
  {
    id: 'pq_36',
    name: 'Kth Largest Element in an Array',
    topic: 'Heap / Priority Queue',
    difficulty: 'Medium',
    pattern: 'Min-Heap of Size K / QuickSelect',
    leetcodeNumber: 215,
    tip: 'Keep a min-heap of size k; the root will always hold the kth largest element in O(n log k).',
  },
  {
    id: 'pq_37',
    name: 'Merge k Sorted Lists',
    topic: 'Heap / Priority Queue',
    difficulty: 'Hard',
    pattern: 'Min-Heap Node Merging',
    leetcodeNumber: 23,
    tip: 'Push list heads into a min-heap; pop minimum and push its next pointer in O(N log k).',
  },
  {
    id: 'pq_38',
    name: 'Task Scheduler',
    topic: 'Heap / Priority Queue',
    difficulty: 'Medium',
    pattern: 'Max Frequency Math',
    leetcodeNumber: 621,
    tip: 'Formula: (maxFreq - 1) * (n + 1) + countOfMaxFreq. Clamp to tasks.length.',
  },

  // ─── Stack & Queue ───
  {
    id: 'pq_39',
    name: 'Valid Parentheses',
    topic: 'Stack & Queue',
    difficulty: 'Easy',
    pattern: 'LIFO Matching Bracket Stack',
    leetcodeNumber: 20,
    tip: 'Push expected closing bracket on open; pop and compare upon encountering closing brackets.',
  },
  {
    id: 'pq_40',
    name: 'Daily Temperatures',
    topic: 'Stack & Queue',
    difficulty: 'Medium',
    pattern: 'Monotonic Decreasing Stack',
    leetcodeNumber: 739,
    tip: 'Store indices of unresolved temperatures; pop when current temperature exceeds stack top.',
  },
  {
    id: 'pq_41',
    name: 'Min Stack',
    topic: 'Stack & Queue',
    difficulty: 'Medium',
    pattern: 'Dual Stack / Value Tuple',
    leetcodeNumber: 155,
    tip: 'Push (val, minValSoFar) pairs so minimum lookup is always strictly O(1).',
  },

  // ─── Backtracking ───
  {
    id: 'pq_42',
    name: 'Subsets',
    topic: 'Backtracking',
    difficulty: 'Medium',
    pattern: 'Include / Exclude Choice Tree',
    leetcodeNumber: 78,
    tip: 'At each index, choose to include current element, recurse, then backtrack and exclude.',
  },
  {
    id: 'pq_43',
    name: 'Combination Sum',
    topic: 'Backtracking',
    difficulty: 'Medium',
    pattern: 'Reuse Candidate Backtracking',
    leetcodeNumber: 39,
    tip: 'Allow same element to be chosen repeatedly until remainder is 0 or negative; avoid duplicate sets with index progression.',
  },
];
